game_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: GameUserBundle:Default:index }

GameUserBundle_user:
        resource: "@GameUserBundle/Resources/config/routing/user.yml"
        prefix:   /user