game_mailing_homepage:
    path:     /hello/{name}
    defaults: { _controller: GameTestBundle:Default:index }

game_mailing_mail:
    pattern:  /mail/{name}
    defaults: { _controller: GameTestBundle:Mail:index }

game_mailing_pdf:
    pattern:  /pdf
    defaults: { _controller: GameTestBundle:Pdf:index }
    
game_mailing_breadcrumps:
    pattern:  /bread
    defaults: { _controller: GameTestBundle:Breadcrumps:index }    