parameters:
#    game_mailing.example.class: Game\Bundle\TestBundle\Example

services:
#    game_mailing.example:
#        class: %game_mailing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
